[package]
name = "ssbh_lib"
version = "0.9.0"
authors = ["ScanMountGoat <>"]
description = "Reading and writing SSBH file formats in Rust"
license = "MIT"
documentation = "https://docs.rs/ssbh_lib"
repository = "https://github.com/ultimate-research/ssbh_lib"
edition = "2018"

[dependencies]
ssbh_write_derive = { version = "0.7", path = "../ssbh_write_derive" }
binread = "2.1.1"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_bytes = { version = "0.11.5", optional = true }
hex = "0.4.2"
byteorder = "1.4.2"
half = "1.7.1"

[features]
default = ["derive_serde"]
derive_serde = ["serde", "serde_bytes"]
hex_buffer = ["derive_serde"]