[package]
name = "ssbh_lib"
version = "0.10.1"
authors = ["ScanMountGoat <>"]
description = "Reading and writing SSBH file formats in Rust"
license = "MIT"
documentation = "https://docs.rs/ssbh_lib"
repository = "https://github.com/ultimate-research/ssbh_lib"
edition = "2018"

[dependencies]
ssbh_write_derive = { version = "^0.10", path = "../ssbh_write_derive" }
binread = "2.1.1"
serde = { version = "1.0", features = ["derive"], optional = true }
arbitrary = { version = "1", optional = true, features = ["derive"] }
serde_bytes = { version = "0.11.5", optional = true }
hex = "0.4.2" # TODO: make hex optional?
half = "1.7.1"

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["derive_serde"]
derive_serde = ["serde", "serde_bytes"]
hex_buffer = ["derive_serde"]