[package]
name = "ssbh_lib_json"
version = "0.16.0"
authors = ["ScanMountGoat <>"]
edition = "2021"

[dependencies]
ssbh_lib = { version = "^0.16", path = "../ssbh_lib", default-features = false, features = ["serde_hex"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
