[package]
name = "ssbh_lib"
version = "0.2.0"
authors = ["ScanMountGoat <>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binread = "1.1.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
hex = "0.4.2"

[lib]
name = "ssbh_lib"
path = "src/lib.rs"

[[bin]]
name = "ssbh_lib_json"
path = "src/main.rs"