[package]
name = "ssbh_lib"
version = "0.1.0"
authors = ["ScanMountGoat <>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binread = "1.0.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }


[lib]
name = "ssbh_lib"
path = "src/lib.rs"

[[bin]]
name = "ssbh_lib_json"
path = "src/main.rs"