[package]
name = "ssbh_write"
version = "0.10.1"
authors = ["ScanMountGoat <>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssbh_write_derive = { version = "^0.10", path = "../ssbh_write_derive" }