[package]
name = "ssbh_data"
version = "0.5.0"
authors = ["ScanMountGoat <>"]
description = "High level data access layer for SSBH formats"
license = "MIT"
documentation = "https://docs.rs/ssbh_data"
repository = "https://github.com/ultimate-research/ssbh_lib"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssbh_lib = { version = "0.5", path = "../" }
binread = "2.1.1"
half = "1.7.1"
ndarray = "0.14.0"
hex = "0.4.2"
