[package]
name = "ssbh_data"
version = "0.1.0"
authors = ["ScanMountGoat <>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssbh_lib = { path = "../" }
binread = "2.0.0"
half = "1.7.1"
ndarray = "0.14.0"
hex = "0.4.2"
