[package]
name = "ssbh_data"
version = "0.10.1"
authors = ["ScanMountGoat <>"]
description = "High level data access layer for SSBH formats"
license = "MIT"
documentation = "https://docs.rs/ssbh_data"
repository = "https://github.com/ultimate-research/ssbh_lib"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssbh_lib = { version = "^0.10", path = "../ssbh_lib", default-features = false }
ssbh_write = { version = "^0.10", path = "../ssbh_write", default-features = false }
binread = "2.1"
half = "1.7"
geometry_tools = "0.2"
itertools = "0.10"
glam = "0.15"
bitbuffer = "0.10.3"
bitvec = "0.22.3"
modular-bitfield = "0.11.2"
hex = "0.4" # TODO: Remove this dependency

[dev-dependencies]
hex = "0.4"
approx = "0.4"
