[package]
name = "ssbh_data"
version = "0.11.0"
authors = ["ScanMountGoat <>"]
description = "High level data access layer for SSBH formats"
license = "MIT"
documentation = "https://docs.rs/ssbh_data"
repository = "https://github.com/ultimate-research/ssbh_lib"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO: Find a way to avoid forcing serde for ssbh_lib.
ssbh_lib = { version = "^0.11", path = "../ssbh_lib", features = ["serde"] }
ssbh_write = { version = "^0.11", path = "../ssbh_write" }
binread = "2.1"
half = "1.7"
geometry_tools = "0.3"
itertools = "0.10"
glam = "0.15"
bitbuffer = "0.10.3"
bitvec = "0.22.3"
modular-bitfield = "0.11.2"
thiserror = "1.0.29"
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
approx = "0.4"
hex-literal = "0.3.3"

[features]
default = ["serde"]